databases:
  - name: dbPortafolio
    databaseName: dbportafolio
    user: basicUser

services:
  - type: web
    name: PorfolioTortugasNinja
    runtime: node
    plan: standard
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: mongodb+srv://basicUser:1234@dbportafolio.evxit.mongodb.net/dbPortafolio?retryWrites=true&w=majority&appName=dbPortafolio
      - key: GMAIL_USER
        value: fernandemarcos11@gmail.com
      - key: GMAIL_PASS
        value: uake nhus vzkp iduc

